export interface Country {
  name: string;
  code: string;
  flag: string;
  iso: string;
  minLen: number;
}

export const COUNTRIES: Country[] = [
  { name: 'United States', code: '+1', flag: '🇺🇸', iso: 'US', minLen: 10 },
  { name: 'United Kingdom', code: '+44', flag: '🇬🇧', iso: 'GB', minLen: 10 },
  { name: 'Canada', code: '+1', flag: '🇨🇦', iso: 'CA', minLen: 10 },
  { name: 'Australia', code: '+61', flag: '🇦🇺', iso: 'AU', minLen: 9 },
  { name: 'Germany', code: '+49', flag: '🇩🇪', iso: 'DE', minLen: 10 },
  { name: 'France', code: '+33', flag: '🇫🇷', iso: 'FR', minLen: 9 },
  { name: 'Spain', code: '+34', flag: '🇪🇸', iso: 'ES', minLen: 9 },
  { name: 'Italy', code: '+39', flag: '🇮🇹', iso: 'IT', minLen: 10 },
  { name: 'India', code: '+91', flag: '🇮🇳', iso: 'IN', minLen: 10 },
  { name: 'China', code: '+86', flag: '🇨🇳', iso: 'CN', minLen: 11 },
  { name: 'Japan', code: '+81', flag: '🇯🇵', iso: 'JP', minLen: 10 },
  { name: 'South Korea', code: '+82', flag: '🇰🇷', iso: 'KR', minLen: 10 },
  { name: 'Brazil', code: '+55', flag: '🇧🇷', iso: 'BR', minLen: 10 },
  { name: 'Mexico', code: '+52', flag: '🇲🇽', iso: 'MX', minLen: 10 },
  { name: 'Argentina', code: '+54', flag: '🇦🇷', iso: 'AR', minLen: 10 },
  { name: 'Russia', code: '+7', flag: '🇷🇺', iso: 'RU', minLen: 10 },
  { name: 'Saudi Arabia', code: '+966', flag: '🇸🇦', iso: 'SA', minLen: 9 },
  { name: 'UAE', code: '+971', flag: '🇦🇪', iso: 'AE', minLen: 9 },
  { name: 'Nigeria', code: '+234', flag: '🇳🇬', iso: 'NG', minLen: 10 },
  { name: 'South Africa', code: '+27', flag: '🇿🇦', iso: 'ZA', minLen: 9 },
  { name: 'Egypt', code: '+20', flag: '🇪🇬', iso: 'EG', minLen: 10 },
  { name: 'Turkey', code: '+90', flag: '🇹🇷', iso: 'TR', minLen: 10 },
  { name: 'Pakistan', code: '+92', flag: '🇵🇰', iso: 'PK', minLen: 10 },
  { name: 'Bangladesh', code: '+880', flag: '🇧🇩', iso: 'BD', minLen: 10 },
  { name: 'Indonesia', code: '+62', flag: '🇮🇩', iso: 'ID', minLen: 10 },
  { name: 'Philippines', code: '+63', flag: '🇵🇭', iso: 'PH', minLen: 10 },
  { name: 'Vietnam', code: '+84', flag: '🇻🇳', iso: 'VN', minLen: 10 },
  { name: 'Thailand', code: '+66', flag: '🇹🇭', iso: 'TH', minLen: 9 },
  { name: 'Malaysia', code: '+60', flag: '🇲🇾', iso: 'MY', minLen: 9 },
  { name: 'Singapore', code: '+65', flag: '🇸🇬', iso: 'SG', minLen: 8 },
  { name: 'Netherlands', code: '+31', flag: '🇳🇱', iso: 'NL', minLen: 9 },
  { name: 'Belgium', code: '+32', flag: '🇧🇪', iso: 'BE', minLen: 9 },
  { name: 'Sweden', code: '+46', flag: '🇸🇪', iso: 'SE', minLen: 9 },
  { name: 'Norway', code: '+47', flag: '🇳🇴', iso: 'NO', minLen: 8 },
  { name: 'Denmark', code: '+45', flag: '🇩🇰', iso: 'DK', minLen: 8 },
  { name: 'Finland', code: '+358', flag: '🇫🇮', iso: 'FI', minLen: 9 },
  { name: 'Switzerland', code: '+41', flag: '🇨🇭', iso: 'CH', minLen: 9 },
  { name: 'Austria', code: '+43', flag: '🇦🇹', iso: 'AT', minLen: 10 },
  { name: 'Poland', code: '+48', flag: '🇵🇱', iso: 'PL', minLen: 9 },
  { name: 'Portugal', code: '+351', flag: '🇵🇹', iso: 'PT', minLen: 9 },
  { name: 'Greece', code: '+30', flag: '🇬🇷', iso: 'GR', minLen: 10 },
  { name: 'Ukraine', code: '+380', flag: '🇺🇦', iso: 'UA', minLen: 9 },
  { name: 'Israel', code: '+972', flag: '🇮🇱', iso: 'IL', minLen: 9 },
  { name: 'Romania', code: '+40', flag: '🇷🇴', iso: 'RO', minLen: 10 },
  { name: 'Hungary', code: '+36', flag: '🇭🇺', iso: 'HU', minLen: 9 },
  { name: 'Czech Republic', code: '+420', flag: '🇨🇿', iso: 'CZ', minLen: 9 },
  { name: 'Ireland', code: '+353', flag: '🇮🇪', iso: 'IE', minLen: 9 },
  { name: 'New Zealand', code: '+64', flag: '🇳🇿', iso: 'NZ', minLen: 9 },
  { name: 'Morocco', code: '+212', flag: '🇲🇦', iso: 'MA', minLen: 9 },
  { name: 'Algeria', code: '+213', flag: '🇩🇿', iso: 'DZ', minLen: 9 },
  { name: 'Tunisia', code: '+216', flag: '🇹🇳', iso: 'TN', minLen: 8 },
  { name: 'Lebanon', code: '+961', flag: '🇱🇧', iso: 'LB', minLen: 7 },
  { name: 'Jordan', code: '+962', flag: '🇯🇴', iso: 'JO', minLen: 9 },
  { name: 'Kuwait', code: '+965', flag: '🇰🇼', iso: 'KW', minLen: 8 },
  { name: 'Qatar', code: '+974', flag: '🇶🇦', iso: 'QA', minLen: 8 },
  { name: 'Bahrain', code: '+973', flag: '🇧🇭', iso: 'BH', minLen: 8 },
  { name: 'Oman', code: '+968', flag: '🇴🇲', iso: 'OM', minLen: 8 },
  { name: 'Iraq', code: '+964', flag: '🇮🇶', iso: 'IQ', minLen: 10 },
  { name: 'Iran', code: '+98', flag: '🇮🇷', iso: 'IR', minLen: 10 },
  { name: 'Kenya', code: '+254', flag: '🇰🇪', iso: 'KE', minLen: 9 },
  { name: 'Ghana', code: '+233', flag: '🇬🇭', iso: 'GH', minLen: 9 },
  { name: 'Ethiopia', code: '+251', flag: '🇪🇹', iso: 'ET', minLen: 9 },
  { name: 'Tanzania', code: '+255', flag: '🇹🇿', iso: 'TZ', minLen: 9 },
  { name: 'Sri Lanka', code: '+94', flag: '🇱🇰', iso: 'LK', minLen: 9 },
  { name: 'Nepal', code: '+977', flag: '🇳🇵', iso: 'NP', minLen: 10 },
  { name: 'Chile', code: '+56', flag: '🇨🇱', iso: 'CL', minLen: 9 },
  { name: 'Colombia', code: '+57', flag: '🇨🇴', iso: 'CO', minLen: 10 },
  { name: 'Peru', code: '+51', flag: '🇵🇪', iso: 'PE', minLen: 9 },
  { name: 'Venezuela', code: '+58', flag: '🇻🇪', iso: 'VE', minLen: 10 },
  { name: 'Ecuador', code: '+593', flag: '🇪🇨', iso: 'EC', minLen: 9 },
  { name: 'Serbia', code: '+381', flag: '🇷🇸', iso: 'RS', minLen: 9 },
  { name: 'Bulgaria', code: '+359', flag: '🇧🇬', iso: 'BG', minLen: 9 },
  { name: 'Croatia', code: '+385', flag: '🇭🇷', iso: 'HR', minLen: 9 },
  { name: 'Slovakia', code: '+421', flag: '🇸🇰', iso: 'SK', minLen: 9 },
];
